//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlicoopmart_nam3_24_10_2021
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class manager_market_smartEntities : DbContext
    {
        public manager_market_smartEntities()
            : base("name=manager_market_smartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_getdata_Result> SP_getdata(string makh)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("Makh", makh) :
                new ObjectParameter("Makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_getdata_Result>("SP_getdata", makhParameter);
        }
    }
}
